### ISSUE TITLE
Framework fails to load if loaded before tree

### ISSUE THREAD

**Issue by Meister1593** [DoubleDeez/MDFramework#1]
**Godot version:**
3.2.1 Mono release 64 bit

**OS/device including version:**
Linux 5.6.7.arch1-1, Arch rolling, 
mono 6.4.0, 
mono-msbuild  16.5.xamarinxplat.2020.01.10.05.36-1

**Issue description:**
When trying to launch server in **_Ready** method with autoloaded MDGameInstance **as GameInstance**,  tree element in MDGameSession class on 87 line is null
![image](https://user-images.githubusercontent.com/7141787/80600288-39779d80-8a3d-11ea-9657-f200a3685c92.png)

Commented zone bellow is where i checked if this occurs when MDGameInstance attached to node and called after some time (it creates server just fine)
![image](https://user-images.githubusercontent.com/7141787/80600498-89566480-8a3d-11ea-8237-614e1bcf4b43.png)
![image](https://user-images.githubusercontent.com/7141787/80600519-907d7280-8a3d-11ea-9687-01e6178e0d16.png)
Test spatial node has attached test.cs script
![image](https://user-images.githubusercontent.com/7141787/80600601-b1de5e80-8a3d-11ea-9b6a-f242fe0fc541.png)

**Comment by DoubleDeez** [comment]
Thanks for reporting those issues
