### ISSUE TITLE
Godot 3.3 support?

### ISSUE THREAD

**Issue by rhofour** [DoubleDeez/MDFramework#113]
The README clearly says this is for Godot 3.2, but the latest stable release is 3.3. What's the status of 3.3 support?

If it's not already working would you accept a PR to add it?

**Comment by DoubleDeez** [comment]
I'd greatly appreciate and accept a PR with 3.3 support - or if it works out of the box for 3.3, let me know and I'll update the readme.

**Comment by Fullbrik** [comment]
I just tested out the networking examples on 3.3.2, and it worked without any modifications. (Tested on Manjaro Linux with NVidia proprietary drivers)
