### ISSUE TITLE
On Screen Debug

### ISSUE THREAD

**Issue by Beider** [DoubleDeez/MDFramework#18]
I added an onscreen debugger to my own fork of MDFramework,

[The class is here](https://github.com/Beider/MDFramework/blob/master/MDInterface/MDOnScreenDebug.cs)

[This video shows it in action](https://vimeo.com/429722455)

This is an example of how it works, it is very easy to use. By default I bound it to F12 in my fork.

```
AddOnScreenDebugInfo("FPS", () => Engine.GetFramesPerSecond().ToString());
AddOnScreenDebugInfo("Static Memory", () => MDStatics.HumanReadableSize(OS.GetStaticMemoryUsage()));
AddOnScreenDebugInfo("Network Active: ", () => MDStatics.IsNetworkActive().ToString());
AddOnScreenDebugInfo("PeerId: ", () => MDStatics.GetPeerId().ToString());
```

Is this something that would fit into the framework? I personally think it is very useful for printing information to the screen during runtime.

**Comment by DoubleDeez** [comment]
This is great, I was planning on adding something like this so I think it would be a great addition.

**Comment by DoubleDeez** [comment]
Adding a field for specifying the color I think would be helpful too.

**Comment by Beider** [comment]
I will add this, do you think we need color per line or just overall color for the whole thing?

**Comment by DoubleDeez** [comment]
I think per line would be ideal

**Comment by Beider** [comment]
Added [color per line on my branch](https://github.com/Beider/MDFramework/blob/master/MDInterface/MDOnScreenDebug.cs). Will be in next pull request.
