### ISSUE TITLE
README.md Game Synchronizer link is broken

### ISSUE THREAD

**Issue by DoubleDeez** [DoubleDeez/MDFramework#20]
Minor issue, the features link is broken:
![image](https://user-images.githubusercontent.com/1893819/85231394-68f6b680-b3ab-11ea-9dfd-38f6acff14ab.png)

**Comment by DoubleDeez** [comment]
@Beider fyi

**Comment by Beider** [comment]
I will take care so this is also fixed the next time I create a pull request. I suspect the readme will need substantial updates after the replicator changes and with the on screen debug.
