### ISSUE TITLE
Split README.md into Wiki

### ISSUE THREAD

**Issue by DoubleDeez** [DoubleDeez/MDFramework#21]
The README should be trimmed down to a short explanation on what the framework is, the features it has, and how to add it to your project. It should link out to the wiki for detailed info on how to use the various features

**Comment by Beider** [comment]
I seem unable to access the wiki at the moment, so wouldn't be able to help with this at the moment. Perhaps it is just because you need to create the first page or it may be related to some other security setting?

**Comment by DoubleDeez** [comment]
I just initialized the wiki, is it editable now? Not too sure how it works with collaborators

**Comment by Beider** [comment]
Seems to work now, I copied the Game Synchronizer section of the readme as a test. I will pretty it up and add more detail later.

https://github.com/DoubleDeez/MDFramework/wiki/Game-Synchronizer

**Comment by Beider** [comment]
I updated the Game Synchronizer page, is this about what we are looking for? Anything else worth adding to the page?

https://github.com/DoubleDeez/MDFramework/wiki/Game-Synchronizer

**Comment by DoubleDeez** [comment]
Looks great. I realized I had opened the wiki to be edited by anyone with a GitHub account. To prevent chaos, I've closed that access and invited you as collaborator
