### ISSUE TITLE
Console not working properly

### ISSUE THREAD

**Issue by Beider** [DoubleDeez/MDFramework#3]
To me it seems there is something wrong with the console currently, I haven't had time to look into it properly yet but I am guessing there is an infinite loop somewhere.

It appears to happen whenever I try to execute a command in the console, the entire game just freezes. I might spend some time on later myself if I find I need the console.

**Comment by DoubleDeez** [comment]
I'm not having this issue, can you attach an example project where this happens?

**Comment by Beider** [comment]
I tested this again and it was working for me now, I don't know why it failed in the past. If I experience it again I will debug it and try to figure out what is going on. For now I will just close this.
