### ISSUE TITLE
Feature: Add more tests

### ISSUE THREAD

**Issue by Beider** [DoubleDeez/MDFramework#35]
We should add more tests (demos) to test everything added in #17 and all features that existed before #17.

- Test all sort of property configuration (unreliable, reliable, interval, onchange, join, one shot)
- Add test for buffered values by adding stuff to the buffer before starting the game (Text box that adds any message to the text)

**Comment by DoubleDeez** [comment]
I'm going to set up a MDFramework-Test repo that we can use for CI and examples (#24)
This should maybe be done there.

**Comment by DoubleDeez** [comment]
Moved to https://github.com/DoubleDeez/MDFramework-Examples/issues/1
