### ISSUE TITLE
Feature: Interpolated Vector3

### ISSUE THREAD

**Issue by Beider** [DoubleDeez/MDFramework#37]
Currently we only have **MDCRMInterpolatedVector2** which is our Vector2, it would be good to also add an interpolated Vector3. If any functionality is duplicated between the two then it should probably be moved into another class that both the interpolated Vectors can inherit from.

**Comment by DoubleDeez** [comment]
I think we should work towards a MDCRMInterpolateFloat that can be extended for Vector2 and Vector3
