### ISSUE TITLE
Setup Discord or something similar?

### ISSUE THREAD

**Issue by Beider** [DoubleDeez/MDFramework#46]
I would suggest setting up a discord for the MDFramework, Godot already has it's own discord server so it would be logical to be on the same platform.

The reason I think this will be a benefit is as more and more people are picking up the framework we don't end up with a bunch of bugs reports here that are just from user error. A discord server would allow people who has more experience with the framework to help new people in real time instead of getting a new bug report every time someone needs help.

That being said if we don't mind bug reports that may not be real bugs on here then a discord server may be redundant.

**Comment by Meister1593** [comment]
Yeah, agree, this would be nice, discord would allow to have fast feedback in case players need help without filing whole bug report. I've struggled a bit in the beginning because lack of documentation before i searched through code.
Just a little bit, and I would ask similar question here.

**Comment by DoubleDeez** [comment]
Done. Here's [the link](https://discord.gg/UH49eHK), I'll add it to Wiki:
