### ISSUE TITLE
Player Initialization Flow & Event

### ISSUE THREAD

**Issue by DoubleDeez** [DoubleDeez/MDFramework#53]
When a player first joins a server there's generally some initialization that needs to occur both from the player and from the server. (eg. authenticating with a platform, sending desired user name or character, etc).

To help facilitate this flow, MDPlayerInfo should provide hooks (virtual methods) for users to add this initialization logic and an Event on MDGameSession should be fired to notify once initialization has completed (or failed).

cc @Meister1593

**Comment by Beider** [comment]
Related to #68, consider fixing these two issues together.

**Comment by DoubleDeez** [comment]
Documented how the player info initialization will be done:
https://github.com/DoubleDeez/MDFramework/wiki/Game-Session#player-info
