### ISSUE TITLE
Rework and document events

### ISSUE THREAD

**Issue by Beider** [DoubleDeez/MDFramework#68]
Currently events are a bit confusing and poorly document in the framework. In particular it is not clear during which event you should do what, one such example is [this issue](https://github.com/DoubleDeez/MDFramework/issues/7).

The goal of this bug would be to rework events so all important events have pre/post events and clear documentation both in code and on the wiki (with examples on the wiki) for which event should do what. And in particular during which events you should not do certain things to avoid bugs.

Here is a list of things that at a minimum should be done in the scope of this bug,

- All framework events should be documented both in wiki and with the appropriate comment
- Add any events that may be relevant (eg. A new player synch / join event where you can spawn the player. [See this issue.](https://github.com/DoubleDeez/MDFramework/issues/7))
- Ensure events are executed at the correct time (eg. for **OnPlayerLeftEvent** often the MDPlayerInfo is removed before the event, this makes no sense).

**Comment by Beider** [comment]
This issue is related to #53, they should probably be fixed together.

**Comment by DoubleDeez** [comment]
Events documented here https://github.com/DoubleDeez/MDFramework/wiki/Game-Session#game-session-events

Will close this issue with PR that aligns the events to match.
