### ISSUE TITLE
Introduce log override to configuration

### ISSUE THREAD

**Issue by Beider** [DoubleDeez/MDFramework#69]
Currently if you want to change loglevel for a particular class you have to go in and change this in the file, it would be nice to be able to just do this from the configuration.

There are two things that could be done here,

1. All loglevels for each separate class could be moved into the configuration allowing you to configure the loglevel in config files instead.
2. Introduce a single configuration override setting, which if set would override all other loglevels.

Personally I think at least number 2 would be nice, number 1 might be a bit more of a pain to maintain.

**Comment by DoubleDeez** [comment]
I think it should work in order of increasing precedence:
- Log Level set in Code
- Log Level set in Config (by default we don't define any here)
- Log Level set by Command

and you should be able to set per log category (as is done in code and command now)
maybe we also have a default in config that overrides the default set by code?
