### ISSUE TITLE
Method number could not be found for class method

### ISSUE THREAD

**Issue by Meister1593** [DoubleDeez/MDFramework#96]
This is another issue related to finding methods needed for reflection to work.

Basically, problem is that we can get method info, but NumberedMethodInfoCache does not have required method, so method is basically missing in cache.
![image](https://user-images.githubusercontent.com/7141787/89128825-7013f700-d509-11ea-9ee0-56144e058c34.png)
![image](https://user-images.githubusercontent.com/7141787/89128840-815d0380-d509-11ea-8e81-3383be2d7add.png)
![image](https://user-images.githubusercontent.com/7141787/89128846-85892100-d509-11ea-8e82-f8d7e5583af6.png)

**Comment by DoubleDeez** [comment]
So it looks like "UpdatedGameStateFromServer" is cached without the "int" param, but you're calling it with the int.
Is it an overloaded method? Trying to figure out how it could get registered without the int.

**Comment by Meister1593** [comment]
> So it looks like "UpdatedGameStateFromServer" is cached without the "int" param, but you're calling it with the int.
> Is it an overloaded method? Trying to figure out how it could get registered without the int.

I cant remember exactly what happened there, but it's not overloaded method for sure. As you can see, it's private method, and i didn't do multiple methods with same name too.

**Comment by DoubleDeez** [comment]
Closing this for now, if someone runs into this again we'll reopen. Without a test case we can't figure out what went wrong.
